# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170522_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='day',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(to='books.Staff'),
        ),
        migrations.AddField(
            model_name='plan',
            name='Not_avaliable_day',
            field=models.CharField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='plan',
            field=models.ManyToManyField(to='books.Plan'),
        ),
    ]
